apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-frontend-deployment
  labels:
    app: streamlit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-frontend
  template:
    metadata:
      labels:
        app: streamlit-frontend
    spec:
      containers:
      - name: streamlit-frontend
        image: ghcr.io/big-data-01-org/frontend/frontend:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-frontend-service
spec:
  type: NodePort
  selector:
    app: streamlit-frontend
  ports:
  - protocol: TCP
    port: 8501
    targetPort: 8501
    nodePort: 30000  # Kubernetes will expose the service on a port in the range 30000-32767
