apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-frontend-deployment
  labels:
    app: streamlit-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit-frontend
  template:
    metadata:
      labels:
        app: streamlit-frontend
    spec:
      containers:
      - name: streamlit-frontend
        image: ghcr.io/big-data-01-org/frontend/frontend:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-frontend-service
spec:
  type: NodePort
  selector:
    app: streamlit-frontend
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 30000 # Kubernetes will expose the service on a port in the range 30000-32767
---
apiVersion: v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka-container
          image: apache/kafka:3.9
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 9098
selector:
  matchLabels:
    app: kafka

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  type: NodePort
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9098
      targetPort: 9098
      nodePort: 30001 # Kubernetes will expose the service on a port in the range 30000-32767
---

